// Generated by https://quicktype.io

import { Product } from "./product.interface";

export interface DetailPostResponse {
  product:         Product;
  amount:          number;
  totalPrice:      number;
  igvImportDetail: number;
  _id:             string;
  __v:             number;
}


